package app.umaia.android.ui.strings

import androidx.compose.runtime.compositionLocalOf

// ── Localised string bundle ───────────────────────────────────────────────────

data class AppStrings(

    // ── Navigation tabs ───────────────────────────────────────────────────────
    val tabTasks: String,
    val tabSteps: String,
    val tabFood: String,
    val tabSeer: String,
    val tabProfile: String,

    // ── Auth ──────────────────────────────────────────────────────────────────
    val signIn: String,
    val signUp: String,
    val email: String,
    val password: String,
    val loading: String,
    val orSeparator: String,
    val continueWithGoogle: String,
    val alreadyHaveAccount: String,
    val noAccount: String,
    val emailConfirmationSent: String,
    val loginTagline: String,
    val agreeToTerms: String,
    val termsError: String,
    val privacyPolicy: String,
    val termsOfService: String,

    // ── Dashboard ─────────────────────────────────────────────────────────────
    val welcome: String,
    val statNur: String,
    val statSteps: String,
    val statTribe: String,
    val statStreak: String,
    val lifeIsMovement: String,
    val nurDecayMessage: (Int) -> String,
    val ok: String,
    val populationGrew: String,
    val populationDeclined: String,
    val welcomeBackTitle: String,
    val welcomeBackMessage: String,
    val letsGo: String,
    val spiritLabel: (Int) -> String,
    val spiritFactors: String,
    val spiritTarget: (Int) -> String,
    val factorFoodWater: String,
    val factorFuel: String,
    val factorKumis: String,
    val factorSongs: String,
    val factorCrafts: String,
    val factorNurActive: String,
    val hintBuildHearthOrBrewery: String,
    val hintBuildCircle: String,
    val hintBuildWorkshop: String,
    val hintWalkForNur: String,
    val warnNoFood: String,
    val warnNoWater: String,
    val warnNoGoods: String,
    val populationSection: String,
    val populationCurrent: String,
    val populationGrowth: String,
    val atCapacity: String,
    val activeCanJoin: String,
    val needSpiritForGrowth: (Int) -> String,
    val buildYurtForCapacity: String,
    val tapToSeeDetails: String,
    val speakToTheSeer: String,
    val discoverRoleEarnNur: String,
    val yourRole: (String) -> String,
    val rewards: String,
    val buildToUnlockRewards: String,
    val rewardClaimed: String,
    val rewardInstruction: (String, String) -> String,
    val claim: String,

    // ── Steps ─────────────────────────────────────────────────────────────────
    val stepsTitle: String,
    val ranking: String,
    val stepPermissionTitle: String,
    val stepPermissionDesc: String,
    val allowAccess: String,
    val stepsToday: String,
    val dailyLimitReached: String,
    val nurEarnedToday: String,
    val shareSteps: String,
    val shareStepsText: (Int, Int) -> String,
    val shareCalendar: String,
    val shareCalendarText: String,
    val stepCalendar: String,
    val calendarTotal: (Int) -> String,
    val monthTotal: String,
    val milestonesReached: String,
    val nextMilestone: (String) -> String,
    val nurFromSteps: String,
    val howNurWorks: String,
    val nurBullet1: String,
    val nurBullet2: String,
    val nurBullet3: String,
    val nurBullet4: String,
    val milestoneStepsProgress: (Int, Int) -> String,
    val dayHeaders: List<String>,

    // ── Leaderboard ───────────────────────────────────────────────────────────
    val leaderboardTitle: String,
    val periodToday: String,
    val periodWeek: String,
    val periodAllTime: String,
    val yourRank: String,
    val stepsCount: (Int) -> String,
    val leaderboardEmpty: String,
    val youIndicator: String,
    val anonymousName: String,

    // ── Profile ───────────────────────────────────────────────────────────────
    val goddessUmaia: String,
    val goddessSubtitle: String,
    val totalNur: String,
    val streak: String,
    val languageLabel: String,
    val themeLabel: String,
    val themeLight: String,
    val themeDark: String,
    val themeAuto: String,
    val changePassword: String,
    val mythologyTitle: String,
    val mythologyText: String,
    val fourPillarsTitle: String,
    val pillars: List<Triple<String, String, String>>,
    val leaveTheSteppe: String,
    val deleteAccount: String,
    val deleteAccountTitle: String,
    val deleteAccountWarning: String,
    val delete: String,
    val cancel: String,
    val changePasswordTitle: String,
    val newPassword: String,
    val confirmPassword: String,
    val passwordUpdated: String,
    val passwordTooShort: String,
    val passwordMismatch: String,
    val update: String,
    val done: String,
    val nomadFallback: String,

    // ── Oracle / Seer ─────────────────────────────────────────────────────────
    val oracleSeerRevealed: String,
    val oracleRetake: String,
    val oracleReturnToVillage: String,
    val oracleRiskFactors: String,
    val oraclePositiveFactors: String,
    val oraclePotentialDeficiencies: String,
    val oracleYears: String,
    val oracleNurAlreadyEarned: String,
    val oracleNurEarned: (Int) -> String,
    val oracleSomethingWrong: String,
    val oracleGoBack: String,
    val oracleContinue: String,

    // ── Season names ──────────────────────────────────────────────────────────
    val seasonLabel: String,
    val seasonSpring: String,
    val seasonSummer: String,
    val seasonAutumn: String,
    val seasonWinter: String,

    // ── Step narratives ───────────────────────────────────────────────────────
    val narrativeZero: String,
    val narrativeUnder1k: String,
    val narrativeUnder3k: String,
    val narrativeUnder6k: String,
    val narrativeUnder10k: String,
    val narrativeUnder15k: String,
    val narrativeMax: String
)

// ── CompositionLocal ──────────────────────────────────────────────────────────

val LocalStrings = compositionLocalOf { EnStrings }

// ── English ───────────────────────────────────────────────────────────────────

val EnStrings = AppStrings(
    tabTasks = "Tasks",
    tabSteps = "Steps",
    tabFood = "Food",
    tabSeer = "Seer",
    tabProfile = "UMAIA",

    signIn = "Sign In",
    signUp = "Sign Up",
    email = "Email",
    password = "Password",
    loading = "Loading…",
    orSeparator = "or",
    continueWithGoogle = "Continue with Google",
    alreadyHaveAccount = "Already have an account? Sign in",
    noAccount = "Don't have an account? Sign up",
    emailConfirmationSent = "Check your email to confirm your account.",
    loginTagline = "Turn your steps to build a new World of Nomads",
    agreeToTerms = "I agree to the",
    termsError = "Please agree to the Terms of Service and Privacy Policy.",
    privacyPolicy = "Privacy Policy",
    termsOfService = "Terms of Service",

    welcome = "Welcome,",
    statNur = "Nur",
    statSteps = "Steps",
    statTribe = "Tribe",
    statStreak = "Streak",
    lifeIsMovement = "Life is movement!",
    nurDecayMessage = { m -> "You've been here ${m}m. Nur is decaying. Go for a walk and come back!" },
    ok = "OK",
    populationGrew = "A new family joined!",
    populationDeclined = "A family left the tribe",
    welcomeBackTitle = "Welcome back! ⚡",
    welcomeBackMessage = "Nur was awarded for your return. Keep the streak going!",
    letsGo = "Let's go!",
    spiritLabel = { s -> "Spirit $s%" },
    spiritFactors = "Spirit Factors",
    spiritTarget = { t -> "Target: $t%" },
    factorFoodWater = "Food & Water",
    factorFuel = "Fuel",
    factorKumis = "Kumis",
    factorSongs = "Songs",
    factorCrafts = "Crafts",
    factorNurActive = "Nur active",
    hintBuildHearthOrBrewery = "Build Hearth or Kumys House",
    hintBuildCircle = "Build Circle of Stories",
    hintBuildWorkshop = "Build Workshop (Tier 2)",
    hintWalkForNur = "Walk to earn Nur",
    warnNoFood = "No food!",
    warnNoWater = "No water!",
    warnNoGoods = "No goods!",
    populationSection = "Population",
    populationCurrent = "Current",
    populationGrowth = "Growth",
    atCapacity = "At capacity",
    activeCanJoin = "Active — new families can join!",
    needSpiritForGrowth = { s -> "Need Spirit ≥ 80 (now $s)" },
    buildYurtForCapacity = "⚠ Build a Yurt for more capacity",
    tapToSeeDetails = "Tap to see details",
    speakToTheSeer = "Speak to the Seer",
    discoverRoleEarnNur = "Discover your role & earn Nur",
    yourRole = { r -> "Your role: $r" },
    rewards = "Rewards",
    buildToUnlockRewards = "Build a Pasture, Well, and Hearth to unlock",
    rewardClaimed = "Reward Claimed!",
    rewardInstruction = { partner, desc -> "Show this screen at $partner to redeem your $desc." },
    claim = "Claim",

    stepsTitle = "Steps",
    ranking = "Ranking",
    stepPermissionTitle = "Step Tracking Permission",
    stepPermissionDesc = "Allow step tracking to earn Nur and unlock quests.",
    allowAccess = "Allow Access",
    stepsToday = "steps today",
    dailyLimitReached = "Daily limit reached! Rest and return tomorrow.",
    nurEarnedToday = "⚡ Nur earned today",
    shareSteps = "Share Steps",
    shareStepsText = { steps, nur -> "I walked $steps steps today and earned $nur Nur in Umaia! 👣⚡" },
    shareCalendar = "Share Calendar",
    shareCalendarText = "Check out my step calendar in Umaia! 📅👣",
    stepCalendar = "Step Calendar",
    calendarTotal = { t -> "Total: ${"%,d".format(t)}" },
    monthTotal = "Month total",
    milestonesReached = "Milestones reached:",
    nextMilestone = { name -> "Next: $name" },
    nurFromSteps = "Nur from Steps",
    howNurWorks = "How Nur Works",
    nurBullet1 = "Steps convert to Nur using a diminishing returns formula",
    nurBullet2 = "Maximum ~50 Nur per day from steps",
    nurBullet3 = "Nur boosts all resource production by +15%",
    nurBullet4 = "Nur decays over time — keep walking!",
    milestoneStepsProgress = { cur, max -> "$cur/$max steps" },
    dayHeaders = listOf("Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"),

    leaderboardTitle = "Leaderboard",
    periodToday = "Today",
    periodWeek = "Week",
    periodAllTime = "All Time",
    yourRank = "Your rank",
    stepsCount = { n -> "%,d steps".format(n) },
    leaderboardEmpty = "No entries yet. Start walking!",
    youIndicator = "You",
    anonymousName = "Anonymous",

    goddessUmaia = "The Goddess Umaia",
    goddessSubtitle = "Guardian of Light, Movement & Life",
    totalNur = "Total Nur",
    streak = "Streak",
    languageLabel = "Language",
    themeLabel = "Theme",
    themeLight = "☀",
    themeDark = "🌙",
    themeAuto = "Auto",
    changePassword = "Change Password",
    mythologyTitle = "The Mythology",
    mythologyText = """When the world was young, the steppe stretched to the very edge of the sky. Across it walked the Nomads — strong, free, born in motion. They knew one truth: the land lives only when feet tread upon it. But one day the steps grew shorter, the rests grew longer, and everything stood still.

Then from the heart of the first dawn, Umaia arose. She was neither flame nor frost — but the breath between them, the force that makes rivers flow and hearts beat. She looked upon the frozen world and wept, and her tears became the first rain.

Umaia proclaimed the First Law: "That which does not move, does not live." With those words the wind stirred the grass, the herds began to run, and the Nomads took their first steps across the steppe.

Now you are part of this movement. Your motion is not just exercise. It is the sacred duty that keeps the world of the Nomads alive.""",
    fourPillarsTitle = "The Four Pillars",
    pillars = listOf(
        Triple("🌱", "Plant & Grow", "Seeds need the vibration of footsteps to sprout. Your movement awakens the earth."),
        Triple("🏕️", "Build & Shelter", "A yurt rises only when hands are busy. Strength comes from daily effort."),
        Triple("👣", "Walk & Move", "Every step generates Nur energy that sustains the world. The path itself is the destination."),
        Triple("✨", "Nur & Light", "Nur is the sacred energy of life. It flows when you move and fades when you stop.")
    ),
    leaveTheSteppe = "Leave the Steppe",
    deleteAccount = "Delete Account",
    deleteAccountTitle = "Delete Account?",
    deleteAccountWarning = "This will permanently delete your account and all data. This cannot be undone.",
    delete = "Delete",
    cancel = "Cancel",
    changePasswordTitle = "Change Password",
    newPassword = "New password",
    confirmPassword = "Confirm password",
    passwordUpdated = "Password updated successfully.",
    passwordTooShort = "Password must be at least 8 characters.",
    passwordMismatch = "Passwords do not match.",
    update = "Update",
    done = "Done",
    nomadFallback = "Nomad",

    oracleSeerRevealed = "THE SEER HAS REVEALED YOUR PATH",
    oracleRetake = "↺ Retake Assessment",
    oracleReturnToVillage = "Return to the village",
    oracleRiskFactors = "Risk Factors",
    oraclePositiveFactors = "Positive Factors",
    oraclePotentialDeficiencies = "Potential Deficiencies",
    oracleYears = "years",
    oracleNurAlreadyEarned = "✓ Nur already earned",
    oracleNurEarned = { n -> "⚡ +$n Nur earned" },
    oracleSomethingWrong = "Something went wrong",
    oracleGoBack = "Go back",
    oracleContinue = "Continue",

    seasonLabel = "Season",
    seasonSpring = "Spring",
    seasonSummer = "Summer",
    seasonAutumn = "Autumn",
    seasonWinter = "Winter",

    narrativeZero = "The steppe awaits your first step...",
    narrativeUnder1k = "A journey begins with a single step.",
    narrativeUnder3k = "Your feet remember the path.",
    narrativeUnder6k = "Nur flows with every step.",
    narrativeUnder10k = "The tribe feels your energy!",
    narrativeUnder15k = "You carry light to the village!",
    narrativeMax = "A legend of the steppe walks today!"
)

// ── Russian ───────────────────────────────────────────────────────────────────

val RuStrings = AppStrings(
    tabTasks = "Задания",
    tabSteps = "Шаги",
    tabFood = "Еда",
    tabSeer = "Провидец",
    tabProfile = "УМАЙЯ",

    signIn = "Войти",
    signUp = "Регистрация",
    email = "Email",
    password = "Пароль",
    loading = "Загрузка…",
    orSeparator = "или",
    continueWithGoogle = "Войти через Google",
    alreadyHaveAccount = "Уже есть аккаунт? Войти",
    noAccount = "Нет аккаунта? Зарегистрироваться",
    emailConfirmationSent = "Проверьте почту для подтверждения аккаунта.",
    loginTagline = "Превращай шаги в мир кочевников",
    agreeToTerms = "Я согласен с условиями",
    termsError = "Пожалуйста, примите условия использования.",
    privacyPolicy = "Политика конфиденциальности",
    termsOfService = "Пользовательское соглашение",

    welcome = "Добро пожаловать,",
    statNur = "Нур",
    statSteps = "Шаги",
    statTribe = "Племя",
    statStreak = "Серия",
    lifeIsMovement = "Жизнь — это движение!",
    nurDecayMessage = { m -> "Вы здесь уже ${m} мин. Нур убывает. Выйдите на прогулку!" },
    ok = "ОК",
    populationGrew = "Новая семья присоединилась!",
    populationDeclined = "Семья покинула племя",
    welcomeBackTitle = "С возвращением! ⚡",
    welcomeBackMessage = "Нур начислен за возвращение. Продолжайте серию!",
    letsGo = "Вперёд!",
    spiritLabel = { s -> "Дух $s%" },
    spiritFactors = "Факторы Духа",
    spiritTarget = { t -> "Цель: $t%" },
    factorFoodWater = "Еда и вода",
    factorFuel = "Топливо",
    factorKumis = "Кумыс",
    factorSongs = "Песни",
    factorCrafts = "Ремёсла",
    factorNurActive = "Нур активен",
    hintBuildHearthOrBrewery = "Постройте Очаг или Кумысхану",
    hintBuildCircle = "Постройте Круг Историй",
    hintBuildWorkshop = "Постройте Мастерскую (уровень 2)",
    hintWalkForNur = "Ходите, чтобы зарабатывать Нур",
    warnNoFood = "Нет еды!",
    warnNoWater = "Нет воды!",
    warnNoGoods = "Нет товаров!",
    populationSection = "Население",
    populationCurrent = "Текущее",
    populationGrowth = "Прирост",
    atCapacity = "Заполнено",
    activeCanJoin = "Активно — новые семьи могут вступить!",
    needSpiritForGrowth = { s -> "Нужен Дух ≥ 80 (сейчас $s)" },
    buildYurtForCapacity = "⚠ Постройте Юрту для вместимости",
    tapToSeeDetails = "Нажмите для деталей",
    speakToTheSeer = "Поговорить с Провидцем",
    discoverRoleEarnNur = "Узнайте свою роль и заработайте Нур",
    yourRole = { r -> "Ваша роль: $r" },
    rewards = "Награды",
    buildToUnlockRewards = "Постройте Пастбище, Колодец и Очаг для разблокировки",
    rewardClaimed = "Награда получена!",
    rewardInstruction = { partner, desc -> "Покажите этот экран в $partner, чтобы получить $desc." },
    claim = "Получить",

    stepsTitle = "Шаги",
    ranking = "Рейтинг",
    stepPermissionTitle = "Разрешение на отслеживание шагов",
    stepPermissionDesc = "Разрешите отслеживание шагов, чтобы зарабатывать Нур и открывать задания.",
    allowAccess = "Разрешить",
    stepsToday = "шагов сегодня",
    dailyLimitReached = "Дневной лимит достигнут! Отдохните и вернитесь завтра.",
    nurEarnedToday = "⚡ Нур за сегодня",
    shareSteps = "Поделиться шагами",
    shareStepsText = { steps, nur -> "Сегодня я прошёл $steps шагов и заработал $nur Нур в Умайе! 👣⚡" },
    shareCalendar = "Поделиться календарём",
    shareCalendarText = "Посмотрите мой календарь шагов в Умайе! 📅👣",
    stepCalendar = "Календарь шагов",
    calendarTotal = { t -> "Итого: ${"%,d".format(t)}" },
    monthTotal = "За месяц",
    milestonesReached = "Достигнутые вехи:",
    nextMilestone = { name -> "Следующая: $name" },
    nurFromSteps = "Нур за шаги",
    howNurWorks = "Как работает Нур",
    nurBullet1 = "Шаги конвертируются в Нур с убывающей отдачей",
    nurBullet2 = "Максимум ~50 Нур в день за шаги",
    nurBullet3 = "Нур увеличивает производство ресурсов на +15%",
    nurBullet4 = "Нур убывает со временем — продолжайте ходить!",
    milestoneStepsProgress = { cur, max -> "$cur/$max шагов" },
    dayHeaders = listOf("Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"),

    leaderboardTitle = "Таблица лидеров",
    periodToday = "Сегодня",
    periodWeek = "Неделя",
    periodAllTime = "Всё время",
    yourRank = "Ваш рейтинг",
    stepsCount = { n -> "%,d шагов".format(n) },
    leaderboardEmpty = "Записей пока нет. Начните ходить!",
    youIndicator = "Вы",
    anonymousName = "Аноним",

    goddessUmaia = "Богиня Умайя",
    goddessSubtitle = "Хранительница Света, Движения и Жизни",
    totalNur = "Всего Нур",
    streak = "Серия",
    languageLabel = "Язык",
    themeLabel = "Тема",
    themeLight = "☀",
    themeDark = "🌙",
    themeAuto = "Авто",
    changePassword = "Сменить пароль",
    mythologyTitle = "Мифология",
    mythologyText = """Когда мир был молод, степь простиралась до самого края неба. По ней ходили Кочевники — сильные, свободные, рождённые в движении. Они знали одну истину: земля живёт лишь тогда, когда её топчут ноги. Но однажды шаги стали короче, отдых — длиннее, и всё замерло.

Тогда из сердца первого рассвета поднялась Умайя. Она была ни огонь, ни мороз — а дыхание между ними, сила, заставляющая реки течь, а сердца — биться. Она взглянула на застывший мир и заплакала, и её слёзы стали первым дождём.

Умайя провозгласила Первый Закон: «То, что не движется, не живёт». При этих словах ветер всколыхнул траву, табуны пустились в бег, и Кочевники сделали первые шаги по степи.

Теперь вы часть этого движения. Ваш шаг — не просто упражнение. Это священный долг, который хранит мир Кочевников живым.""",
    fourPillarsTitle = "Четыре Столпа",
    pillars = listOf(
        Triple("🌱", "Сади и Расти", "Семенам нужна вибрация шагов, чтобы прорасти. Ваше движение пробуждает землю."),
        Triple("🏕️", "Строй и Защищай", "Юрта поднимается лишь там, где заняты руки. Сила приходит через ежедневный труд."),
        Triple("👣", "Иди и Двигайся", "Каждый шаг создаёт энергию Нур, поддерживающую мир. Сам путь — и есть цель."),
        Triple("✨", "Нур и Свет", "Нур — священная энергия жизни. Она течёт, когда вы движетесь, и гаснет, когда вы останавливаетесь.")
    ),
    leaveTheSteppe = "Покинуть степь",
    deleteAccount = "Удалить аккаунт",
    deleteAccountTitle = "Удалить аккаунт?",
    deleteAccountWarning = "Аккаунт и все данные будут удалены безвозвратно. Отменить невозможно.",
    delete = "Удалить",
    cancel = "Отмена",
    changePasswordTitle = "Смена пароля",
    newPassword = "Новый пароль",
    confirmPassword = "Подтвердите пароль",
    passwordUpdated = "Пароль успешно обновлён.",
    passwordTooShort = "Пароль должен содержать не менее 8 символов.",
    passwordMismatch = "Пароли не совпадают.",
    update = "Обновить",
    done = "Готово",
    nomadFallback = "Кочевник",

    oracleSeerRevealed = "ПРОВИДЕЦ ОТКРЫЛ ВАШ ПУТЬ",
    oracleRetake = "↺ Пройти заново",
    oracleReturnToVillage = "Вернуться в деревню",
    oracleRiskFactors = "Факторы риска",
    oraclePositiveFactors = "Положительные факторы",
    oraclePotentialDeficiencies = "Возможные дефициты",
    oracleYears = "лет",
    oracleNurAlreadyEarned = "✓ Нур уже начислен",
    oracleNurEarned = { n -> "⚡ +$n Нур начислено" },
    oracleSomethingWrong = "Что-то пошло не так",
    oracleGoBack = "Назад",
    oracleContinue = "Продолжить",

    seasonLabel = "Сезон",
    seasonSpring = "Весна",
    seasonSummer = "Лето",
    seasonAutumn = "Осень",
    seasonWinter = "Зима",

    narrativeZero = "Степь ждёт первого шага...",
    narrativeUnder1k = "Путь начинается с одного шага.",
    narrativeUnder3k = "Твои ноги помнят дорогу.",
    narrativeUnder6k = "Нур течёт с каждым шагом.",
    narrativeUnder10k = "Племя чувствует твою энергию!",
    narrativeUnder15k = "Ты несёшь свет в деревню!",
    narrativeMax = "Легенда степи шагает сегодня!"
)

// ── Kazakh ───────────────────────────────────────────────────────────────────

val KkStrings = AppStrings(
    tabTasks = "Тапсырмалар",
    tabSteps = "Қадамдар",
    tabFood = "Азық",
    tabSeer = "Көріпкел",
    tabProfile = "ҰМАЙ",

    signIn = "Кіру",
    signUp = "Тіркелу",
    email = "Эл. пошта",
    password = "Құпиясөз",
    loading = "Жүктелуде…",
    orSeparator = "немесе",
    continueWithGoogle = "Google арқылы жалғастыру",
    alreadyHaveAccount = "Аккаунтыңыз бар ма? Кіру",
    noAccount = "Аккаунтыңыз жоқ па? Тіркелу",
    emailConfirmationSent = "Аккаунтты растау үшін поштаңызды тексеріңіз.",
    loginTagline = "Қадамдарыңды Көшпенділер әлеміне айналдыр",
    agreeToTerms = "Мен шарттарымен келісемін",
    termsError = "Пайдалану шарттары мен Құпиялылық саясатын қабылдаңыз.",
    privacyPolicy = "Құпиялылық саясаты",
    termsOfService = "Пайдалану шарттары",

    welcome = "Қош келдің,",
    statNur = "Нұр",
    statSteps = "Қадамдар",
    statTribe = "Ру",
    statStreak = "Серия",
    lifeIsMovement = "Өмір — қозғалыс!",
    nurDecayMessage = { m -> "Сіз мұнда ${m} мин болдыңыз. Нұр азаюда. Серуенге шығыңыз!" },
    ok = "ОК",
    populationGrew = "Жаңа отбасы қосылды!",
    populationDeclined = "Бір отбасы руды тастап кетті",
    welcomeBackTitle = "Қайта оралуыңызбен! ⚡",
    welcomeBackMessage = "Қайтқаныңыз үшін Нұр берілді. Серияны жалғастырыңыз!",
    letsGo = "Жүр!",
    spiritLabel = { s -> "Рух $s%" },
    spiritFactors = "Рух факторлары",
    spiritTarget = { t -> "Мақсат: $t%" },
    factorFoodWater = "Азық пен Су",
    factorFuel = "Отын",
    factorKumis = "Қымыз",
    factorSongs = "Жырлар",
    factorCrafts = "Қолөнер",
    factorNurActive = "Нұр белсенді",
    hintBuildHearthOrBrewery = "Ошақ немесе Қымызхана сал",
    hintBuildCircle = "Жырлар Шеңберін сал",
    hintBuildWorkshop = "Шеберхана сал (2-деңгей)",
    hintWalkForNur = "Нұр жинау үшін жүр",
    warnNoFood = "Азық жоқ!",
    warnNoWater = "Су жоқ!",
    warnNoGoods = "Тауар жоқ!",
    populationSection = "Халық",
    populationCurrent = "Қазіргі",
    populationGrowth = "Өсу",
    atCapacity = "Толық сыйымдылықта",
    activeCanJoin = "Белсенді — жаңа отбасылар қосыла алады!",
    needSpiritForGrowth = { s -> "Рух ≥ 80 керек (қазір $s)" },
    buildYurtForCapacity = "⚠ Сыйымдылық үшін Киіз үй тік",
    tapToSeeDetails = "Толық ақпарат үшін басыңыз",
    speakToTheSeer = "Көріпкелмен сөйлесу",
    discoverRoleEarnNur = "Рөліңді біл және Нұр жина",
    yourRole = { r -> "Сенің рөлің: $r" },
    rewards = "Марапаттар",
    buildToUnlockRewards = "Ашу үшін Жайылым, Құдық және Ошақ сал",
    rewardClaimed = "Марапат алынды!",
    rewardInstruction = { partner, desc -> "$desc алу үшін бұл экранды $partner дүкенінде көрсетіңіз." },
    claim = "Алу",

    stepsTitle = "Қадамдар",
    ranking = "Рейтинг",
    stepPermissionTitle = "Қадам бақылау рұқсаты",
    stepPermissionDesc = "Нұр жинау және тапсырмаларды ашу үшін қадам бақылауына рұқсат беріңіз.",
    allowAccess = "Рұқсат беру",
    stepsToday = "бүгінгі қадам",
    dailyLimitReached = "Күндік лимитке жеттіңіз! Демалып, ертең оралыңыз.",
    nurEarnedToday = "⚡ Бүгін алынған Нұр",
    shareSteps = "Қадамдармен бөлісу",
    shareStepsText = { steps, nur -> "Бүгін $steps қадам жүріп, Umaia-да $nur Нұр жинадым! 👣⚡" },
    shareCalendar = "Күнтізбемен бөлісу",
    shareCalendarText = "Umaia-дағы қадам күнтізбемді көріңіз! 📅👣",
    stepCalendar = "Қадам күнтізбесі",
    calendarTotal = { t -> "Барлығы: ${"%,d".format(t)}" },
    monthTotal = "Ай бойынша",
    milestonesReached = "Жеткен белестер:",
    nextMilestone = { name -> "Келесі: $name" },
    nurFromSteps = "Қадамдардан Нұр",
    howNurWorks = "Нұр қалай жұмыс істейді",
    nurBullet1 = "Қадамдар азаятын формуламен Нұрға айналады",
    nurBullet2 = "Қадамдардан күніне ең көбі ~50 Нұр",
    nurBullet3 = "Нұр барлық ресурс өндірісін +15% арттырады",
    nurBullet4 = "Нұр уақыт өте азаяды — жүруді жалғастырыңыз!",
    milestoneStepsProgress = { cur, max -> "$cur/$max қадам" },
    dayHeaders = listOf("Дс", "Сс", "Ср", "Бс", "Жм", "Сб", "Жс"),

    leaderboardTitle = "Көшбасшылар кестесі",
    periodToday = "Бүгін",
    periodWeek = "Осы апта",
    periodAllTime = "Барлық уақыт",
    yourRank = "Сенің орның",
    stepsCount = { n -> "%,d қадам".format(n) },
    leaderboardEmpty = "Әзірше жазбалар жоқ. Жүруді бастаңыз!",
    youIndicator = "Сен",
    anonymousName = "Көшпенді",

    goddessUmaia = "Ұмай ана",
    goddessSubtitle = "Жарық, Қозғалыс және Өмірдің Қорғаушысы",
    totalNur = "Барлық Нұр",
    streak = "Серия",
    languageLabel = "Тіл",
    themeLabel = "Тема",
    themeLight = "☀",
    themeDark = "🌙",
    themeAuto = "Авто",
    changePassword = "Құпиясөзді өзгерту",
    mythologyTitle = "Мифология",
    mythologyText = """Әлем жас кезінде дала аспан шетіне дейін созылатын. Онда Көшпенділер жүретін — мықты, еркін, қозғалыста туған. Олар бір ақиқатты білетін: жер тек аяқ басқанда ғана тіршілік етеді. Бірақ бір күні қадамдар қысқарды, демалыстар ұзарды және бәрі тоқтады.

Сол кезде алғашқы таңның жүрегінен Ұмай ана көтерілді. Ол от та, аяз да емес — олардың арасындағы тыныс, өзендерді ағызып, жүректерді соғатын күш еді. Ол мұздаған әлемге қарап жылады, және оның жастары алғашқы жаңбыр болды.

Ұмай ана Бірінші Заңды жариялады: «Қозғалмайтын нәрсе тірі емес». Сол сөздермен жел шөпті желбіретті, жылқылар шабуылға шықты, және Көшпенділер дала бойынша алғашқы қадамдарын жасады.

Енді сен осы қозғалыстың бір бөлігісің. Сенің қозғалысың тек жаттығу емес. Бұл Көшпенділер әлемін тірі ұстайтын қасиетті борыш.""",
    fourPillarsTitle = "Төрт тірек",
    pillars = listOf(
        Triple("🌱", "Ек және Өсір", "Дәндерге өну үшін қадамдардың дірілі қажет. Сенің қозғалысың жерді оятады."),
        Triple("🏕️", "Сал және Қорға", "Киіз үй тек қолдар жұмыс істегенде көтеріледі. Күш күнделікті еңбектен келеді."),
        Triple("👣", "Жүр және Қозғал", "Әр қадам әлемді ұстайтын Нұр энергиясын тудырады. Жолдың өзі — мақсат."),
        Triple("✨", "Нұр және Жарық", "Нұр — өмірдің қасиетті энергиясы. Қозғалғанда ағады, тоқтағанда сөнеді.")
    ),
    leaveTheSteppe = "Даладан шығу",
    deleteAccount = "Аккаунтты жою",
    deleteAccountTitle = "Аккаунтты жою керек пе?",
    deleteAccountWarning = "Аккаунт пен барлық деректер біржола жойылады. Бұл қайтымсыз.",
    delete = "Жою",
    cancel = "Болдырмау",
    changePasswordTitle = "Құпиясөзді өзгерту",
    newPassword = "Жаңа құпиясөз",
    confirmPassword = "Құпиясөзді растаңыз",
    passwordUpdated = "Құпиясөз сәтті жаңартылды.",
    passwordTooShort = "Құпиясөз кемінде 8 таңбадан тұруы керек.",
    passwordMismatch = "Құпиясөздер сәйкес келмейді.",
    update = "Жаңарту",
    done = "Дайын",
    nomadFallback = "Көшпенді",

    oracleSeerRevealed = "КӨРІПКЕЛ ЖОЛЫҢДЫ АШТЫ",
    oracleRetake = "↺ Қайта тапсыру",
    oracleReturnToVillage = "Ауылға оралу",
    oracleRiskFactors = "Қауіп факторлары",
    oraclePositiveFactors = "Оң факторлар",
    oraclePotentialDeficiencies = "Ықтимал тапшылықтар",
    oracleYears = "жас",
    oracleNurAlreadyEarned = "✓ Нұр бұрын алынған",
    oracleNurEarned = { n -> "⚡ +$n Нұр алынды" },
    oracleSomethingWrong = "Бірдеңе дұрыс болмады",
    oracleGoBack = "Артқа",
    oracleContinue = "Жалғастыру",

    seasonLabel = "Мезгіл",
    seasonSpring = "Көктем",
    seasonSummer = "Жаз",
    seasonAutumn = "Күз",
    seasonWinter = "Қыс",

    narrativeZero = "Дала сенің алғашқы қадамыңды күтеді...",
    narrativeUnder1k = "Аяғыңның астында шөп сыбдырлайды. Жол басталды.",
    narrativeUnder3k = "Ауылға жылылық жайылады.",
    narrativeUnder6k = "Нұр әр қадаммен ағады.",
    narrativeUnder10k = "Ру сенің энергияңды сезеді!",
    narrativeUnder15k = "Сен ауылға жарық алып келесің!",
    narrativeMax = "Сен аңыздардың арасында жүресің. Дала саған бас иеді."
)
