package app.umaia.android.domain.model

enum class NutritionCategory(
    val id: String,
    val icon: String,
    val labelEn: String,
    val labelRu: String,
    val labelKk: String
) {
    AVOID("AVOID", "⛔", "Poisons of the Steppe", "Яды Степи", "Дала Уы"),
    SWAP("SWAP",   "🔄", "Healer's Swaps",        "Замены Целителя", "Емшінің Алмастыруы"),
    ORDER("ORDER", "📋", "The Ritual of the Meal", "Ритуал Трапезы", "Ас Рәсімі"),
    EAT("EAT",     "✅", "Gifts of the Earth",     "Дары Земли", "Жер Сыйлары"),
    HOW("HOW",     "🍳", "The Way of Eating",      "Путь Питания", "Тамақтану Жолы"),
    WHEN("WHEN",   "⏰", "Rhythms of the Body",    "Ритмы Тела", "Дене Ырғағы"),
}

data class NutritionCard(
    val id: String,
    val category: NutritionCategory,
    val icon: String,
    val title: String,
    val titleRu: String,
    val titleKk: String,
    val body: String,
    val bodyRu: String,
    val bodyKk: String,
    val swap: String? = null,
    val swapRu: String? = null,
    val swapKk: String? = null,
    val source: String,
    val scienceBased: Boolean = false
)

data class NutritionQuizOption(
    val text: String,
    val textRu: String,
    val textKk: String,
    val correct: Boolean
)

data class NutritionQuiz(
    val id: String,
    val cardId: String,
    val question: String,
    val questionRu: String,
    val questionKk: String,
    val options: List<NutritionQuizOption>,
    val nurReward: Int
)

val allNutritionCards: List<NutritionCard> = listOf(
    // ── AVOID ──
    NutritionCard("A1", NutritionCategory.AVOID, "🥓",
        "The hidden poison in cured meat",
        "Скрытый яд в копчёном мясе",
        "Ысталған еттегі жасырын у",
        "The healers have long warned: cured and smoked meat — sausages, bacon, ham — carries darkness within. The world's wisest healers confirmed it. Every 50g daily raises the risk of grave illness by 18%.",
        "Целители давно предупреждали: копчёное и вяленое мясо — колбасы, бекон, ветчина — несёт в себе тьму. Мудрейшие целители мира подтвердили: каждые 50г в день повышают риск тяжёлой болезни на 18%.",
        "Емшілер баяғыдан ескертіп келеді: ысталған және тұздалған ет — шұжық, бекон, ветчина — ішінде қараңғылық алып жүреді. Дүниенің ең дана емшілері растады: күнделікті 50 г ет ауыр ауру қаупін 18%-ға арттырады.",
        swap = "Fresh chicken, fish, eggs, beans, lentils or tofu",
        swapRu = "Свежая курица, рыба, яйца, бобы, чечевица или тофу",
        swapKk = "Жас тауық еті, балық, жұмыртқа, бұршақ, жасымық немесе тофу",
        source = "WHO/IARC Press Release 240"),
    NutritionCard("A2", NutritionCategory.AVOID, "🥩",
        "Red meat — no more than 3 times a week",
        "Красное мясо — не чаще 3 раз в неделю",
        "Қызыл ет — аптасына 3 реттен артық емес",
        "The tribe eats red meat with respect and restraint. Beef, pork, lamb — limit to 350–500g per week. Excess brings illness that weakens the strongest warrior.",
        "Племя ест красное мясо с уважением и умеренностью. Говядина, свинина, баранина — не более 350–500г в неделю. Избыток несёт болезнь, что ослабит сильнейшего воина.",
        "Ру қызыл етті құрметпен әрі шамамен жейді. Сиыр, шошқа, қой еті — аптасына 350–500 г-нан артық емес. Артық мөлшер ең мықты жауынгерді де әлсірететін ауру әкеледі.",
        swap = "Fish, poultry, eggs, legumes or plant proteins",
        swapRu = "Рыба, птица, яйца, бобовые или растительные белки",
        swapKk = "Балық, құс еті, жұмыртқа, бұршақ тұқымдастар немесе өсімдік белоктары",
        source = "WCRF Cancer Prevention Recommendations"),
    NutritionCard("A3", NutritionCategory.AVOID, "🧂",
        "Salt — the silent enemy",
        "Соль — тихий враг",
        "Тұз — үнсіз дұшпан",
        "The healers say: no more than one pinch of salt per day (5g). Most of it hides in prepared foods, bread and sauces. Excess salt raises blood pressure and weakens the heart.",
        "Целители говорят: не более одной щепотки соли в день (5г). Большая часть прячется в готовых продуктах, хлебе и соусах. Избыток соли повышает давление и ослабляет сердце.",
        "Емшілер айтады: күніне бір шөкімнен артық тұз жеме (5 г). Оның көп бөлігі дайын тағамдарда, нанда және тұздықтарда жасырылған. Артық тұз қан қысымын көтеріп, жүректі әлсіретеді.",
        swap = "Herbs, spices, lemon, garlic and vinegar",
        swapRu = "Травы, специи, лимон, чеснок и уксус",
        swapKk = "Шөптер, дәмдеуіштер, лимон, сарымсақ және сірке суы",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("A4", NutritionCategory.AVOID, "🍟",
        "Trans fats — eliminate completely",
        "Трансжиры — исключить полностью",
        "Транс-майлар — толық жою",
        "These unnatural fats hide in margarine, fast food, and packaged cookies. Even a small amount damages the heart. Look for \"partially hydrogenated oils\" on labels and avoid them.",
        "Эти неестественные жиры прячутся в маргарине, фаст-фуде и пакетированном печенье. Даже малое количество вредит сердцу. Ищите на этикетках «частично гидрогенизированные масла» и избегайте их.",
        "Бұл табиғи емес майлар маргаринде, фастфудта және пакеттелген печеньеде жасырылған. Тіпті аз мөлшері жүрекке зиян келтіреді. Жапсырмадан «ішінара гидрогенделген майларды» іздеп, олардан аулақ болыңыз.",
        swap = "Olive oil, avocado, nuts and seeds",
        swapRu = "Оливковое масло, авокадо, орехи и семена",
        swapKk = "Зәйтүн майы, авокадо, жаңғақ және дән",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("A5", NutritionCategory.AVOID, "🥤",
        "Sweet drinks are disguised candy",
        "Сладкие напитки — замаскированные конфеты",
        "Тәтті сусындар — бүркемеленген кәмпит",
        "The sugar in sodas, energy drinks and juice hits the blood like a raid — fast and devastating. No fibre to slow it. The wisest nomads drink water.",
        "Сахар в газировке, энергетиках и соках бьёт по крови как набег — быстро и разрушительно. Нет клетчатки, чтобы замедлить. Мудрейшие кочевники пьют воду.",
        "Газды сусындардағы, энергетиктердегі және шырындардағы қант қанға шабуылдағандай тез әрі жойқын соққы береді. Оны бәсеңдететін талшық жоқ. Дана көшпенділер су ішеді.",
        swap = "Water, sparkling water, unsweetened tea",
        swapRu = "Вода, газированная вода, несладкий чай",
        swapKk = "Су, газды су, тәттілендірілмеген шай",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("A6", NutritionCategory.AVOID, "🍬",
        "Free sugars — less is safer",
        "Свободные сахара — чем меньше, тем безопаснее",
        "Еркін қанттар — аз болған сайын қауіпсіз",
        "For a nomad eating 2000 calories: no more than 50g of sugar (12 teaspoons). Ideally under 25g (6 tsp). This includes honey, syrups and juice.",
        "Для кочевника на 2000 калорий: не более 50г сахара (12 чайных ложек). Идеально — менее 25г (6 ч.л.). Сюда входят мёд, сиропы и соки.",
        "2000 калория тұтынатын көшпендіге: күніне 50 г-нан (12 шай қасық) артық қант жеме. Ең дұрысы — 25 г-нан (6 шай қасық) аз. Бұған бал, сироптар мен шырын кіреді.",
        swap = "Whole fruit for sweetness — fibre slows absorption",
        swapRu = "Цельные фрукты для сладости — клетчатка замедляет усвоение",
        swapKk = "Тәттілік үшін бүтін жеміс — талшық сіңуін бәсеңдетеді",
        source = "WHO Healthy Diet Fact Sheet"),

    // ── SWAP ──
    NutritionCard("S1", NutritionCategory.SWAP, "🍊",
        "Eat the orange, don't drink it",
        "Ешь апельсин, а не пей его",
        "Апельсинді же, бірақ ішпе",
        "When you squeeze the fruit, you lose its armour — the fibre. Sugar hits your blood unprotected. One glass = sugar from 3 oranges with none of the shield.",
        "Когда выжимаешь фрукт, теряешь его броню — клетчатку. Сахар бьёт по крови без защиты. Один стакан = сахар из 3 апельсинов без щита.",
        "Жемісті сыққанда сен оның сауытынан — талшықтан айрыласың. Қант қанға қорғансыз соққы береді. Бір стақан = 3 апельсиндегі қант, қалқансыз.",
        swap = "Whole fruit over juice. Juice? Max 150ml.",
        swapRu = "Цельный фрукт вместо сока. Сок? Макс. 150мл.",
        swapKk = "Шырынның орнына бүтін жеміс. Шырын? Ең көбі 150 мл.",
        source = "WHO free sugars guideline"),
    NutritionCard("S2", NutritionCategory.SWAP, "🫒",
        "Replace bad fats with good ones",
        "Замени плохие жиры на хорошие",
        "Жаман майларды жақсысымен алмастыр",
        "The healer teaches: butter, palm oil, fatty meat — these are heavy fats that clog the rivers of the body. Replace with olive oil, nuts, fish — they keep the flow clear.",
        "Целитель учит: масло, пальмовое масло, жирное мясо — это тяжёлые жиры, забивающие реки тела. Замени на оливковое масло, орехи, рыбу — они сохраняют чистоту потока.",
        "Емші үйретеді: сары май, пальма майы, майлы ет — бұл дене өзендерін бітейтін ауыр майлар. Оларды зәйтүн майы, жаңғақ, балықпен алмастыр — олар ағынның тазалығын сақтайды.",
        swap = "Butter → avocado. Lard → olive oil. Full-fat → low-fat dairy.",
        swapRu = "Масло → авокадо. Сало → оливковое масло. Жирное → нежирное молочное.",
        swapKk = "Сары май → авокадо. Май → зәйтүн майы. Майлы → майсыз сүт өнімдері.",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("S3", NutritionCategory.SWAP, "🍞",
        "White bread → whole grain",
        "Белый хлеб → цельнозерновой",
        "Ақ нан → тұтас дәнді нан",
        "White flour is grain stripped of its strength — no fibre, no vitamins. Whole grains feed you slowly and steadily, like a fire that lasts all night.",
        "Белая мука — зерно, лишённое своей силы: ни клетчатки, ни витаминов. Цельные зёрна питают медленно и стабильно, как огонь, горящий всю ночь.",
        "Ақ ұн — күш-қуатынан айырылған дән: талшық та, витамин де жоқ. Тұтас дәндер түні бойы жанатын от сияқты баяу әрі тұрақты қоректендіреді.",
        swap = "White rice → brown rice/quinoa. White bread → wholegrain.",
        swapRu = "Белый рис → бурый рис/киноа. Белый хлеб → цельнозерновой.",
        swapKk = "Ақ күріш → қоңыр күріш/киноа. Ақ нан → тұтас дәнді нан.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("S4", NutritionCategory.SWAP, "🥜",
        "Snacks from the earth, not the factory",
        "Перекусы от земли, а не с завода",
        "Жеңіл-желпі тағам зауыттан емес, жерден",
        "The steppe provides: raw vegetables, fruit, nuts, seeds. Factory snacks are full of salt, sugar and empty promises.",
        "Степь даёт: сырые овощи, фрукты, орехи, семена. Заводские перекусы полны соли, сахара и пустых обещаний.",
        "Дала береді: шикі көкөніс, жеміс, жаңғақ, дән. Зауыт тағамдары тұзға, қантқа және бос уәдеге толы.",
        swap = "Crisps → nuts. Biscuits → carrot sticks. Candy → whole fruit.",
        swapRu = "Чипсы → орехи. Печенье → морковные палочки. Конфеты → цельные фрукты.",
        swapKk = "Чипсы → жаңғақ. Печенье → сәбіз таяқшалары. Кәмпит → бүтін жеміс.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("S5", NutritionCategory.SWAP, "🥪",
        "Deli meat → fresh protein",
        "Колбаса → свежий белок",
        "Шұжық → жас белок",
        "Deli meats carry the same darkness as processed meat. A daily sandwich with ham is already at the danger threshold. Choose fresh protein instead.",
        "Колбасные изделия несут ту же тьму, что и переработанное мясо. Ежедневный бутерброд с ветчиной уже на пороге опасности. Выбирай свежий белок.",
        "Шұжық өнімдері өңделген ет сияқты қараңғылықты алып жүреді. Ветчинамен күнделікті бутерброд — қауіп табалдырығы. Оның орнына жас белокты таңда.",
        swap = "Tuna, boiled egg, fresh chicken, hummus or beans",
        swapRu = "Тунец, варёное яйцо, свежая курица, хумус или бобы",
        swapKk = "Тунец, пісірілген жұмыртқа, жас тауық еті, хумус немесе бұршақ",
        source = "WHO/IARC Processed Meat Classification"),

    // ── ORDER ──
    NutritionCard("O1", NutritionCategory.ORDER, "🥗",
        "Start every meal with vegetables",
        "Начинай каждый приём пищи с овощей",
        "Әр тамақты көкөністен баста",
        "The healer's ancient rule: vegetables first, then protein, then grains. The fibre creates a shield that slows the rush of sugar into your blood.",
        "Древнее правило целителя: сначала овощи, потом белок, потом крупы. Клетчатка создаёт щит, замедляющий поток сахара в кровь.",
        "Емшінің көне ережесі: алдымен көкөніс, сосын белок, сосын жарма. Талшық қанға қант ағынын бәсеңдететін қалқан жасайды.",
        swap = "① Salad → ② Protein (fish, eggs) → ③ Carbs (rice, bread) last",
        swapRu = "① Салат → ② Белок (рыба, яйца) → ③ Углеводы (рис, хлеб) последними",
        swapKk = "① Салат → ② Белок (балық, жұмыртқа) → ③ Көмірсулар (күріш, нан) соңында",
        source = "PMC3882489 / Diabetes Care 2025", scienceBased = true),
    NutritionCard("O2", NutritionCategory.ORDER, "🍚",
        "Never start with carbs alone",
        "Никогда не начинай с одних углеводов",
        "Ешқашан тек көмірсулардан бастама",
        "Eating starchy food on an empty stomach is like charging into battle without armour. Protein and fibre first reduce the blood sugar spike by up to 37%.",
        "Есть крахмалистую пищу на голодный желудок — как идти в бой без доспехов. Белок и клетчатка сначала снижают скачок сахара в крови на 37%.",
        "Аш қарынға крахмалды тағам жеу — сауытсыз шайқасқа шабумен тең. Алдымен белок пен талшық қандағы қанттың секірісін 37%-ға дейін төмендетеді.",
        swap = "Skip the bread basket. Eat salad before the main dish.",
        swapRu = "Пропусти хлебную корзину. Ешь салат перед основным блюдом.",
        swapKk = "Нан себетін өткізіп жібер. Негізгі тағам алдында салат же.",
        source = "Shukla et al. Diabetes Care 2015", scienceBased = true),
    NutritionCard("O3", NutritionCategory.ORDER, "💧",
        "Water is the drink of the wise",
        "Вода — напиток мудрых",
        "Су — даналардың сусыны",
        "Sweet drinks with food double the sugar assault on your body. The tribe's healers always drank water or unsweetened tea with meals.",
        "Сладкие напитки с едой удваивают сахарный удар по телу. Целители племени всегда пили воду или несладкий чай за трапезой.",
        "Тамақпен бірге тәтті сусындар денеге қант соққысын екі есе арттырады. Ру емшілері тамақ кезінде әрдайым су немесе тәттілендірілмеген шай ішетін.",
        swap = "Water or unsweetened tea at every meal. Avoid juice with food.",
        swapRu = "Вода или несладкий чай за каждой трапезой. Избегай сока с едой.",
        swapKk = "Әр тамақта су немесе тәттілендірілмеген шай. Тамақпен шырын ішуден аулақ бол.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("O4", NutritionCategory.ORDER, "🍽️",
        "Eat slowly — listen to your body",
        "Ешь медленно — слушай своё тело",
        "Баяу же — денеңді тыңда",
        "A nomad who eats too fast outruns their own body's signals. Put the fork down between bites. Chew thoroughly. Your body needs time to tell you it's had enough.",
        "Кочевник, который ест слишком быстро, обгоняет сигналы своего тела. Клади вилку между укусами. Тщательно жуй. Телу нужно время сказать, что оно сыто.",
        "Тым тез жейтін көшпенді өз денесінің сигналдарын басып озады. Жұтым арасында шанышқыны қой. Мұқият шайна. Денеге тойғанын айту үшін уақыт керек.",
        swap = "Eat mindfully at a table. Avoid screens during meals.",
        swapRu = "Ешь осознанно за столом. Избегай экранов во время еды.",
        swapKk = "Үстел басында саналы түрде же. Тамақ кезінде экрандардан аулақ бол.",
        source = "WHO Healthy Diet Fact Sheet"),

    // ── EAT ──
    NutritionCard("E1", NutritionCategory.EAT, "🥦",
        "400g of the earth's gifts daily",
        "400г даров земли ежедневно",
        "Күніне 400 г жер сыйы",
        "The healer prescribes: at least 400g (5 portions) of varied fruits and vegetables every day — the earth's medicine.",
        "Целитель прописывает: минимум 400г (5 порций) разнообразных фруктов и овощей каждый день — лекарство земли.",
        "Емші ұсынады: күн сайын кемінде 400 г (5 порция) әртүрлі жеміс пен көкөніс — жердің дәрісі.",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("E2", NutritionCategory.EAT, "🫘",
        "Whole grains, legumes and nuts",
        "Цельные злаки, бобовые и орехи",
        "Тұтас дәндер, бұршақ тұқымдастар және жаңғақ",
        "The backbone of the nomad's diet. Fibre, protein and minerals that keep the tribe strong through any season.",
        "Основа рациона кочевника. Клетчатка, белок и минералы, которые делают племя сильным в любой сезон.",
        "Көшпенді рационының негізі. Руды кез келген мезгілде мықты ұстайтын талшық, белок пен минералдар.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("E3", NutritionCategory.EAT, "🧂",
        "Salt — one pinch, no more",
        "Соль — одна щепотка, не больше",
        "Тұз — бір шөкім, одан артық емес",
        "Under 5g salt per day. High sodium raises blood pressure — a silent thief of the warrior's strength.",
        "Менее 5г соли в день. Избыток натрия повышает давление — тихий вор силы воина.",
        "Күніне 5 г-нан аз тұз. Артық натрий қан қысымын көтереді — жауынгер күшінің үнсіз ұрысы.",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("E4", NutritionCategory.EAT, "🍯",
        "Sugars — the less, the stronger you are",
        "Сахар — чем меньше, тем ты сильнее",
        "Қант — азайтқан сайын мықты боласың",
        "Under 10% of daily energy from free sugars (ideally 5%). Includes honey, syrups and fruit juices.",
        "Менее 10% дневной энергии от свободных сахаров (идеально 5%). Включает мёд, сиропы и фруктовые соки.",
        "Еркін қанттардан күндік энергияның 10%-нан азы (ең дұрысы 5%). Бұған бал, сироптар мен жеміс шырындары кіреді.",
        source = "WHO Europe Nutrition Fact Sheet"),
    NutritionCard("E5", NutritionCategory.EAT, "🥑",
        "Fat — choose the right oils",
        "Жиры — выбирай правильные масла",
        "Майлар — дұрыс майларды таңда",
        "Total fat under 30% of calories. Replace heavy fats with olive oil, nuts, avocado — they nourish without clogging.",
        "Общий жир — менее 30% калорий. Замени тяжёлые жиры на оливковое масло, орехи, авокадо — они питают, не закупоривая.",
        "Жалпы май — калорияның 30%-нан азы. Ауыр майларды зәйтүн майы, жаңғақ, авокадомен алмастыр — олар бітемей қоректендіреді.",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("E6", NutritionCategory.EAT, "🚫",
        "Eliminate trans fats completely",
        "Полностью исключи трансжиры",
        "Транс-майларды толығымен алып таста",
        "These factory-made fats are poison to the heart. Check labels for \"partially hydrogenated oils.\"",
        "Эти фабричные жиры — яд для сердца. Проверяй этикетки на «частично гидрогенизированные масла».",
        "Бұл зауыт майлары — жүрекке у. Жапсырмадан «ішінара гидрогенделген майларды» тексер.",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("E7", NutritionCategory.EAT, "🐟",
        "Lean proteins in moderation",
        "Нежирные белки в умеренности",
        "Майсыз белокты шамамен",
        "Fish, eggs, poultry, dairy — the tribe's proven sources of strength. Red and processed meats — with great restraint.",
        "Рыба, яйца, птица, молочные продукты — проверенные источники силы племени. Красное и переработанное мясо — с большой сдержанностью.",
        "Балық, жұмыртқа, құс еті, сүт өнімдері — рудың тексерілген күш көздері. Қызыл және өңделген ет — өте ұстамдылықпен.",
        source = "FAO/WHO Joint Statement 2024"),
    NutritionCard("E8", NutritionCategory.EAT, "🚰",
        "Water above all drinks",
        "Вода — превыше всех напитков",
        "Су — барлық сусыннан жоғары",
        "Water is the blood of the earth. Unsweetened tea or coffee in moderation are also worthy choices.",
        "Вода — кровь земли. Несладкий чай или кофе в умеренности тоже достойный выбор.",
        "Су — жердің қаны. Тәттілендірілмеген шай немесе кофе де шамамен лайықты таңдау.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("E9", NutritionCategory.EAT, "🏪",
        "Eat what the earth gives, not the factory",
        "Ешь то, что даёт земля, а не завод",
        "Зауыт емес, жер бергенді же",
        "Minimally processed foods, low in unhealthy fats and sugar — the foundation of the nomad's strength.",
        "Минимально обработанные продукты, с малым содержанием вредных жиров и сахара — основа силы кочевника.",
        "Зиянды май мен қанты аз, аз өңделген өнімдер — көшпенді күшінің негізі.",
        source = "WHO Healthy Diet Fact Sheet 2026"),

    // ── HOW ──
    NutritionCard("H1", NutritionCategory.HOW, "🌈",
        "Eat diverse foods every day",
        "Ешь разнообразную пищу каждый день",
        "Күн сайын әртүрлі тағам же",
        "A tribe that eats only one thing grows weak. Diversity in food ensures all the body's needs are met.",
        "Племя, которое ест только одно, слабеет. Разнообразие в пище обеспечивает все потребности тела.",
        "Тек бір нәрсе жейтін ру әлсірейді. Тамақтағы әртүрлілік дененің барлық қажеттілігін қамтамасыз етеді.",
        source = "FAO/WHO Joint Statement 2024"),
    NutritionCard("H2", NutritionCategory.HOW, "🫕",
        "Cook vegetables gently",
        "Готовь овощи бережно",
        "Көкөністерді абайлап пісір",
        "The healer warns: excessive heat destroys the life force in vegetables. Steam or lightly cook them.",
        "Целитель предупреждает: чрезмерный жар уничтожает жизненную силу овощей. Готовь на пару или слегка обжаривай.",
        "Емші ескертеді: шамадан тыс жылу көкөністердің тіршілік күшін жояды. Буға пісір немесе жеңіл қуыр.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("H3", NutritionCategory.HOW, "🥕",
        "Raw snacks from the earth",
        "Сырые перекусы от земли",
        "Жерден шикі жеңіл тағамдар",
        "Between meals: raw vegetables and fresh fruit. What grows from the earth is always better than what comes from a factory.",
        "Между приёмами пищи: сырые овощи и свежие фрукты. То, что растёт из земли, всегда лучше того, что приходит с завода.",
        "Тамақ аралығында: шикі көкөніс пен жас жеміс. Жерде өсетін нәрсе зауыттан келетін нәрседен әрдайым артық.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("H4", NutritionCategory.HOW, "🌿",
        "Season with herbs, not salt",
        "Приправляй травами, а не солью",
        "Тұзбен емес, шөптермен дәмде",
        "The steppe offers countless herbs and spices. They add flavour and healing power, while excess salt only brings harm.",
        "Степь предлагает бесчисленные травы и специи. Они добавляют вкус и целебную силу, тогда как избыток соли несёт лишь вред.",
        "Дала сансыз шөп пен дәмдеуіш ұсынады. Олар дәм мен шипалық күш қосады, ал артық тұз тек зиян әкеледі.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("H5", NutritionCategory.HOW, "⚖️",
        "Match calories to your journey",
        "Соотноси калории с путешествием",
        "Калорияны сапарыңа сәйкестендір",
        "Eat what you need for the day's journey — no more, no less. A nomad who carries too much cannot walk far.",
        "Ешь столько, сколько нужно для дневного пути — не больше, не меньше. Кочевник, несущий слишком много, не уйдёт далеко.",
        "Күндік жолға қанша қажет болса, сонша же — артық та, кем де емес. Тым көп нәрсе көтерген көшпенді алысқа бара алмайды.",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("H6", NutritionCategory.HOW, "🍽️",
        "Balance all food groups",
        "Балансируй все группы продуктов",
        "Барлық тағам топтарын теңестір",
        "Protein, fats, carbs — like the three legs of a yurt. Remove one and the whole structure collapses.",
        "Белки, жиры, углеводы — как три ноги юрты. Убери одну — и вся конструкция рухнет.",
        "Белоктар, майлар, көмірсулар — киіз үйдің үш аяғы сияқты. Біреуін алсаң — бүкіл құрылым құлайды.",
        source = "FAO/WHO Joint Statement 2024"),
    NutritionCard("H7", NutritionCategory.HOW, "👶",
        "Teach children to eat well",
        "Учи детей правильно питаться",
        "Балаларды дұрыс тамақтандыруға үйрет",
        "The habits of a young nomad become the strength of an elder. What a child learns at the table carries through a lifetime.",
        "Привычки юного кочевника становятся силой старейшины. Что ребёнок усвоит за столом, пронесёт через всю жизнь.",
        "Жас көшпендінің әдеттері — ақсақалдың күші. Бала үстел басында үйренгенін бүкіл өмірі бойы алып жүреді.",
        source = "WHO Healthy Diet Fact Sheet 2026"),

    // ── WHEN ──
    NutritionCard("W1", NutritionCategory.WHEN, "🔄",
        "Eat well throughout life",
        "Питайся правильно всю жизнь",
        "Бүкіл өмір бойы дұрыс тамақтан",
        "The path of good food has no end. From the first breath to the last campfire, nourishment shapes destiny.",
        "Путь хорошей еды не имеет конца. От первого вздоха до последнего костра — питание формирует судьбу.",
        "Жақсы тағам жолының соңы жоқ. Алғашқы тыныстан соңғы отқа дейін — тамақтану тағдырды қалыптастырады.",
        source = "WHO Healthy Diet Fact Sheet"),
    NutritionCard("W2", NutritionCategory.WHEN, "👧",
        "Children need the best food",
        "Детям нужна лучшая еда",
        "Балаларға ең жақсы тағам керек",
        "A child's body and mind are being built. Give them the strongest materials — fresh food, variety, love.",
        "Тело и разум ребёнка строятся. Дай им прочнейшие материалы — свежую еду, разнообразие, любовь.",
        "Бала денесі мен ақыл-ойы құрылып жатыр. Оларға ең мықты материалдарды бер — жас тағам, әртүрлілік, махаббат.",
        source = "WHO Keys to Eating Well"),
    NutritionCard("W3", NutritionCategory.WHEN, "📅",
        "Consistent, moderate meals",
        "Регулярные, умеренные приёмы пищи",
        "Тұрақты, шамалы тамақтану",
        "The steppe does not reward feast-and-famine. Steady, moderate meals keep your energy flowing like a river, not a flash flood.",
        "Степь не награждает за пиршество и голод. Стабильные, умеренные приёмы пищи поддерживают энергию как река, а не как паводок.",
        "Дала той мен ашаршылық үшін сыйламайды. Тұрақты, шамалы тамақтану энергияңды тасқын емес, өзен сияқты ағынды ұстайды.",
        source = "WHO Europe Nutrition Fact Sheet"),
)

val allNutritionQuizzes: List<NutritionQuiz> = listOf(
    NutritionQuiz("Q_A1", "A1",
        "How dangerous is processed meat according to the world's healers?",
        "Насколько опасно переработанное мясо по мнению мировых целителей?",
        "Дүние емшілерінің пікірінше, өңделген ет қаншалықты қауіпті?",
        listOf(
            NutritionQuizOption("Not classified as dangerous", "Не классифицировано как опасное", "Қауіпті деп жіктелмеген", false),
            NutritionQuizOption("Confirmed carcinogen (Group 1)", "Подтверждённый канцероген (Группа 1)", "Расталған канцероген (1-топ)", true),
            NutritionQuizOption("Possibly carcinogenic", "Возможно канцерогенно", "Мүмкін канцерогенді", false),
        ), nurReward = 8),
    NutritionQuiz("Q_A3", "A3",
        "How much salt per day do the healers recommend?",
        "Сколько соли в день рекомендуют целители?",
        "Емшілер күніне қанша тұз ұсынады?",
        listOf(
            NutritionQuizOption("Under 10g", "Менее 10г", "10 г-нан аз", false),
            NutritionQuizOption("Under 8g", "Менее 8г", "8 г-нан аз", false),
            NutritionQuizOption("Under 5g", "Менее 5г", "5 г-нан аз", true),
        ), nurReward = 8),
    NutritionQuiz("Q_A4", "A4",
        "How much trans fat is safe?",
        "Сколько трансжиров безопасно?",
        "Қанша транс-май қауіпсіз?",
        listOf(
            NutritionQuizOption("Zero — eliminate completely", "Ноль — исключить полностью", "Нөл — толығымен алып таста", true),
            NutritionQuizOption("Up to 5g per day", "До 5г в день", "Күніне 5 г-ға дейін", false),
            NutritionQuizOption("Up to 2% of calories", "До 2% калорий", "Калорияның 2%-на дейін", false),
        ), nurReward = 8),
    NutritionQuiz("Q_S1", "S1",
        "Why is whole orange better than orange juice?",
        "Почему цельный апельсин лучше апельсинового сока?",
        "Неге бүтін апельсин апельсин шырынынан жақсы?",
        listOf(
            NutritionQuizOption("It has more sugar", "В нём больше сахара", "Онда қант көп", false),
            NutritionQuizOption("Fibre slows sugar absorption", "Клетчатка замедляет усвоение сахара", "Талшық қанттың сіңуін бәсеңдетеді", true),
            NutritionQuizOption("It has fewer vitamins", "В нём меньше витаминов", "Онда витамин аз", false),
        ), nurReward = 10),
    NutritionQuiz("Q_S3", "S3",
        "Why choose whole grains over white?",
        "Почему стоит выбирать цельные злаки вместо белых?",
        "Неге ақ дәндердің орнына тұтас дәндерді таңдау керек?",
        listOf(
            NutritionQuizOption("They taste better", "Они вкуснее", "Олар дәмдірек", false),
            NutritionQuizOption("They are cheaper", "Они дешевле", "Олар арзанырақ", false),
            NutritionQuizOption("They keep fibre, vitamins and steady blood sugar", "Сохраняют клетчатку, витамины и стабильный сахар в крови", "Талшықты, витаминдерді және қандағы қантты тұрақты сақтайды", true),
        ), nurReward = 10),
    NutritionQuiz("Q_O1", "O1",
        "In what order should you eat a meal?",
        "В каком порядке нужно есть?",
        "Тамақты қандай ретпен жеу керек?",
        listOf(
            NutritionQuizOption("Carbs → protein → vegetables", "Углеводы → белок → овощи", "Көмірсулар → белок → көкөніс", false),
            NutritionQuizOption("Protein → carbs → vegetables", "Белок → углеводы → овощи", "Белок → көмірсулар → көкөніс", false),
            NutritionQuizOption("Vegetables → protein → carbs", "Овощи → белок → углеводы", "Көкөніс → белок → көмірсулар", true),
        ), nurReward = 10),
    NutritionQuiz("Q_O4", "O4",
        "Why should you eat slowly?",
        "Почему нужно есть медленно?",
        "Неге баяу жеу керек?",
        listOf(
            NutritionQuizOption("To give your body time to signal fullness", "Чтобы дать телу время подать сигнал сытости", "Денеге тою сигналын беруге уақыт беру үшін", true),
            NutritionQuizOption("To save food", "Чтобы экономить еду", "Тамақты үнемдеу үшін", false),
            NutritionQuizOption("It doesn't matter how fast you eat", "Не важно, как быстро ешь", "Қаншалықты тез жегенің маңызды емес", false),
        ), nurReward = 10),
    NutritionQuiz("Q_E1", "E1",
        "How much fruit & veg does the healer recommend daily?",
        "Сколько фруктов и овощей целитель рекомендует ежедневно?",
        "Емші күніне қанша жеміс пен көкөніс ұсынады?",
        listOf(
            NutritionQuizOption("200g (2 portions)", "200г (2 порции)", "200 г (2 порция)", false),
            NutritionQuizOption("400g (5 portions)", "400г (5 порций)", "400 г (5 порция)", true),
            NutritionQuizOption("600g (8 portions)", "600г (8 порций)", "600 г (8 порция)", false),
        ), nurReward = 8),
    NutritionQuiz("Q_E5", "E5",
        "What should total fat be limited to?",
        "До скольких процентов нужно ограничить общий жир?",
        "Жалпы майды қанша пайызға шектеу керек?",
        listOf(
            NutritionQuizOption("50% of calories", "50% калорий", "Калорияның 50%-ы", false),
            NutritionQuizOption("10% of calories", "10% калорий", "Калорияның 10%-ы", false),
            NutritionQuizOption("30% of calories", "30% калорий", "Калорияның 30%-ы", true),
        ), nurReward = 8),
    NutritionQuiz("Q_H5", "H5",
        "What should calorie intake match?",
        "Чему должно соответствовать потребление калорий?",
        "Калория тұтынуы неге сәйкес болуы керек?",
        listOf(
            NutritionQuizOption("Your energy expenditure / activity level", "Вашим энергозатратам / уровню активности", "Сіздің энергия шығыныңыз / белсенділік деңгейіңізге", true),
            NutritionQuizOption("Your age only", "Только вашему возрасту", "Тек жасыңызға", false),
            NutritionQuizOption("Your weight only", "Только вашему весу", "Тек салмағыңызға", false),
        ), nurReward = 10),
    NutritionQuiz("Q_H1", "H1",
        "Why is food diversity important?",
        "Почему важно разнообразие в еде?",
        "Неге тамақтағы әртүрлілік маңызды?",
        listOf(
            NutritionQuizOption("It makes meals more interesting", "Это делает еду интереснее", "Бұл тамақты қызықтырақ етеді", false),
            NutritionQuizOption("It ensures all the body's nutritional needs are met", "Это обеспечивает все потребности тела в питании", "Бұл дененің барлық қоректік қажеттіліктерін қамтамасыз етеді", true),
            NutritionQuizOption("It is cheaper to eat different foods", "Разную еду дешевле покупать", "Әртүрлі тағамды сатып алу арзанырақ", false),
        ), nurReward = 10),
    NutritionQuiz("Q_H4", "H4",
        "What should you use instead of salt for seasoning?",
        "Чем приправлять еду вместо соли?",
        "Тұздың орнына тамақты немен дәмдеу керек?",
        listOf(
            NutritionQuizOption("More sugar", "Больше сахара", "Көбірек қант", false),
            NutritionQuizOption("Herbs and spices", "Травы и специи", "Шөптер мен дәмдеуіштер", true),
            NutritionQuizOption("Butter", "Масло", "Сары май", false),
        ), nurReward = 10),
    NutritionQuiz("Q_W1", "W1",
        "When should you follow a healthy diet?",
        "Когда нужно придерживаться здорового питания?",
        "Салауатты тамақтануды қашан ұстану керек?",
        listOf(
            NutritionQuizOption("Only during illness", "Только во время болезни", "Тек ауру кезінде", false),
            NutritionQuizOption("Only in childhood", "Только в детстве", "Тек балалық шақта", false),
            NutritionQuizOption("Throughout your entire life", "На протяжении всей жизни", "Бүкіл өмір бойы", true),
        ), nurReward = 10),
    NutritionQuiz("Q_W2", "W2",
        "Why do children need the best food?",
        "Почему детям нужна лучшая еда?",
        "Неге балаларға ең жақсы тағам қажет?",
        listOf(
            NutritionQuizOption("Their body and mind are being built", "Их тело и разум строятся", "Олардың денесі мен ақыл-ойы құрылуда", true),
            NutritionQuizOption("They are pickier eaters", "Они более привередливы в еде", "Олар тамақта талғампаздау", false),
            NutritionQuizOption("They burn more calories playing", "Они сжигают больше калорий в играх", "Олар ойында көбірек калория жағады", false),
        ), nurReward = 10),
    NutritionQuiz("Q_W3", "W3",
        "What is the best eating pattern?",
        "Какой режим питания лучше всего?",
        "Қандай тамақтану тәртібі ең жақсы?",
        listOf(
            NutritionQuizOption("One big feast per day", "Одно большое застолье в день", "Күніне бір үлкен той", false),
            NutritionQuizOption("Consistent, moderate meals", "Регулярные, умеренные приёмы пищи", "Тұрақты, шамалы тамақтану", true),
            NutritionQuizOption("Eating only when very hungry", "Есть только когда очень голоден", "Тек қатты ашыққанда ғана тамақтану", false),
        ), nurReward = 10),
)

fun cardsForCategory(category: NutritionCategory): List<NutritionCard> =
    allNutritionCards.filter { it.category == category }

fun quizzesForCategory(category: NutritionCategory): List<NutritionQuiz> {
    val cardIds = cardsForCategory(category).map { it.id }.toSet()
    return allNutritionQuizzes.filter { it.cardId in cardIds }
}

// ── Locale-aware accessors ───────────────────────────────────────────────────
//
// Mirrors `OracleQuestion.localizedText(code)`. Data classes hold EN/RU/KK in
// parallel; the screen passes the active code from `LocalStrings.current.code`.
// Anything other than "en"/"kk" falls back to RU (default-shipped market lang).

fun NutritionCategory.localizedLabel(code: String): String = when (code) {
    "en" -> labelEn
    "kk" -> labelKk
    else -> labelRu
}

fun NutritionCard.localizedTitle(code: String): String = when (code) {
    "en" -> title
    "kk" -> titleKk
    else -> titleRu
}

fun NutritionCard.localizedBody(code: String): String = when (code) {
    "en" -> body
    "kk" -> bodyKk
    else -> bodyRu
}

fun NutritionCard.localizedSwap(code: String): String? = when (code) {
    "en" -> swap
    "kk" -> swapKk
    else -> swapRu
}

fun NutritionQuiz.localizedQuestion(code: String): String = when (code) {
    "en" -> question
    "kk" -> questionKk
    else -> questionRu
}

fun NutritionQuizOption.localizedText(code: String): String = when (code) {
    "en" -> text
    "kk" -> textKk
    else -> textRu
}
