package app.umaia.android.domain.model

enum class QuestType { BUILD, ASSIGN, EXPLORE, STEPS }

data class QuestDef(
    val id: Int,
    val type: QuestType,
    val target: String?,
    val nameEn: String,
    val nameRu: String,
    val nameKk: String,
    val descEn: String,
    val descRu: String,
    val descKk: String,
    val nurReward: Int
)

val allQuests: List<QuestDef> = listOf(
    QuestDef(1, QuestType.BUILD, "pasture",
        "Build a Pasture", "Построй Пастбище", "Жайылым сал",
        "Your tribe needs food. Build a Pasture to feed the horses.",
        "Племени нужна еда. Построй Пастбище для лошадей.",
        "Руыңа азық керек. Жылқыларды тамақтандыру үшін Жайылым сал.", 5),
    QuestDef(2, QuestType.BUILD, "well",
        "Build a Well", "Построй Колодец", "Құдық қаз",
        "Water is life. Dig a well for clean water.",
        "Вода — это жизнь. Выкопай колодец.",
        "Су — өмір. Таза су үшін құдық қаз.", 5),
    QuestDef(3, QuestType.BUILD, "hearth",
        "Build a Hearth", "Построй Очаг", "Ошақ жақ",
        "Light the sacred fire to warm your tribe.",
        "Разожги священный огонь для тепла.",
        "Руыңды жылыту үшін қасиетті отты жақ.", 8),
    QuestDef(4, QuestType.ASSIGN, "any",
        "Assign Workers", "Назначь Работников", "Жұмысшыларды тағайында",
        "Assign at least 3 workers to your buildings.",
        "Назначь минимум 3 работника в постройки.",
        "Құрылыстарға кем дегенде 3 жұмысшы тағайында.", 5),
    QuestDef(5, QuestType.EXPLORE, "panels",
        "Explore Info Panels", "Изучи информационные панели", "Ақпарат панельдерін зертте",
        "Open the Spirit and Population panels to learn about your tribe.",
        "Открой панели Духа и Населения, чтобы узнать о племени.",
        "Руың туралы білу үшін Рух және Халық панельдерін аш.", 5),
    QuestDef(11, QuestType.EXPLORE, "oracle",
        "Consult the Seer", "Обратись к Провидцу", "Көріпкелге бар",
        "Complete the Seer assessment to discover your tribal role.",
        "Пройди оценку Провидца, чтобы узнать свою роль.",
        "Рудағы рөліңді білу үшін Көріпкелдің бағалауынан өт.", 10),
    QuestDef(12, QuestType.EXPLORE, "nutrition",
        "Learn the Wisdom of Food", "Познай Мудрость Еды", "Азық Даналығын таны",
        "Complete at least one Food category to prove your knowledge.",
        "Пройди хотя бы одну категорию Еды.",
        "Білімің үшін кем дегенде бір Азық санатын өт.", 10),
    QuestDef(6, QuestType.STEPS, "sync",
        "Sync Your Steps", "Синхронизируй Шаги", "Қадамдарыңды синхронда",
        "Walk and sync your steps to earn Nur energy.",
        "Ходи и синхронизируй шаги для Нура.",
        "Нұр энергиясын жинау үшін жүріп, қадамдарыңды синхронда.", 10),
    QuestDef(7, QuestType.BUILD, "woodcamp",
        "Build a Woodcamp", "Построй Лесоруб", "Ағаш кесу лагерін сал",
        "Wood is scarce. Build a camp to gather it.",
        "Дерево — дефицит. Построй лагерь для сбора.",
        "Ағаш тапшы. Оны жинау үшін лагерь сал.", 10),
    QuestDef(8, QuestType.BUILD, "loom",
        "Build a Loom", "Построй Ткацкий станок", "Тоқыма станогын сал",
        "Weave felt for advanced buildings.",
        "Ткай войлок для продвинутых построек.",
        "Дамыған құрылыстар үшін киіз тоқы.", 10),
    QuestDef(9, QuestType.BUILD, "brewery",
        "Build a Kumys House", "Построй Кумысхану", "Қымызхана сал",
        "Kumis lifts the Spirit of your tribe.",
        "Кумыс поднимает Дух племени.",
        "Қымыз руыңның Рухын көтереді.", 15),
    QuestDef(10, QuestType.BUILD, "yurt",
        "Build a Yurt", "Построй Юрту", "Киіз үй тік",
        "Expand your tribe — build housing for new families.",
        "Расширь племя — построй жильё для новых семей.",
        "Руыңды кеңейт — жаңа отбасылар үшін баспана тік.", 20),
)

fun currentQuest(completedIds: List<Int>): QuestDef? =
    allQuests.firstOrNull { it.id != 0 && it.id !in completedIds }
